---
title: "Semana 2"
format: pdf
editor: visual
---

## Operações Matemáticas Básicas

```{python}
print("Olá, Mundo")

## adição
2 + 3

## subtração
5 - 3

## Multiplicação
5 * 6

## Divisão
12 / 6

## Valor Absoluto
abs(-5)

## Potenciação
2 ** 5
```

### Importando a Biblioteca Math para operações mais compplexas

```{python}
import math

## Raiz quadrada
math.sqrt(9)

## Exponencial
math.exp(8)

## Logaritmo base 10
math.log10(10)

## Logaritmo Natural
math.log(2)

## Fatorial
math.factorial(5)

## Funções Trigonométricas
math.sin(6)

```

## Tipos de Variáveis

Tipos básicos de variáveis:

-   int --> Inteiro
-   float --> números decimais
-   str --> conjunto de caracteres

Exemplo:

```{python}
x = 10 # int
y = 3.14 # float
nome = "Eberechi"

print(type(x))
print(type(y))
print(type(nome))

```

Em Python, o nome de uma variável deve sempre começar com uma letra. Após a primeira letra, podem ser utilizados números e o caractere sublinhado (\_). O sublinhado também é permitido como primeiro caractere, embora seu uso inicial seja maiscomum para indicar variáveis internas ou especiais.

## Strings

Em Python, strings são sequências de caracteres, como palavras, frases ou textos completos. Podem ser definidas usando aspas simples ('...') ou aspas duplas ("..."). Para exibir o conteúdo de uma string na tela, utiliza-se a função print().

```{python}
mensagem = "Vamos, Furacão"
print(mensagem)

```

Para juntar (concatenar) duas ou mais strings em Python, utiliza-se o operador +. É importante que todos os elementos sejam strings; caso contrário, será necessário converter ovalor com str().

```{python}
nome = "Eberechi"
sobrenome = "Eze"
nome_completo_s_espaço = nome + sobrenome
nome_completo = nome + " " + sobrenome
print(nome_completo_s_espaço)
print(nome_completo)

```

### Manipulação de Strings

```{python}
teste = "O Bruno Zapelli foi o cara da partida"
len(teste) # retorna o tamanho do string
teste.capitalize() # retorna a string com a primeira letra maiúscula
teste.count("a") # informa quantas vezes o caractere aparece na string
teste.startswith("O") # verifica se a string inicia com determinada sequência
teste.endswith("b") #verifica se a string termina com determinada sequência
teste.isalnum() # verifica se a string consiste apenas em caracteres alfanuméricos
teste.isalpha() # verifica se a string consiste apenas em letras
teste.islower() # verifica se a string consiste apenas em caracteres minúsculos
teste.isupper() # verifica se a string consiste apenas em caracteres maiúsculos
teste.lower() # retorna a string com todos os caracteres em minúsculo
teste.upper() # retorna a string com todos os caracteres em maiúsculo
teste.swapcase() #inverte maiúsculas e minúsculas
teste.title() #deixa todas as primeiras letras em maiúsculo
teste.split() #transforma a string em uma lista, dividindo todas as suas partes
teste.replace("cara","homem") # substitui S1 por S2 na string
teste.find("r") # retorna o índice da primeira ocorrência de um caractere (ou -1 se não encontrado)
teste2 = "Zapelli"
teste2.ljust(25) # retorna a string para um tamanho mínimo, alinhando à esquerda
teste2.rjust(25) # retorna a string para um tamanho mínimo, alinhando à direita
teste2.center(25) # retorna a string para um tamanho mínimo, centralizando
teste2.lstrip() # remove os espaços à esquerda da string
teste2.rstrip() # remove os espaços à direita da string
teste2.strip() # remove os espaços em branco dos dois lados da string

```

### Operações com Strings

```{python}


```


