---
title: "Semana 7 - slide 10"
format: html
editor: visual
---

# Semana 7 - Slide 10

feito no 'https://sqliteonline.com/' com dados de 'https://docs.ufpr.br/\~lmelo/sqlcursos.txt'

```{SQL}
CREATE TABLE `cursos` (
	`Ano` INT(4),
	`Curso` VARCHAR(50),
	`Turno` VARCHAR(3),
	`DuraĂ§ĂŁo` INT(1),
	`Vagas` INT(4),
	`Inscritos` INT(3),
	`Ingressantes` INT(2),
	`Matriculados` INT(3),
	`Concluintes` INT(2)
)

INSERT INTO cursos (Ano,Curso,Turno,`DuraĂ§ĂŁo`,Vagas,Inscritos,Ingressantes,Matriculados,Concluintes)
VALUES
(2017,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,359,30,107,22),
(2017,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',2,30,62,29,83,10),
(2016,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,474,30,131,16),
(2016,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',2,30,53,30,44,15),
(2015,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,649,38,132,19),
(2015,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',2,30,49,27,61,18),
(2014,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,511,26,108,11),
(2014,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',2,30,42,27,44,10),
(2013,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,465,27,90,10),
(2013,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',2,30,28,10,29,9),
(2018,'TĂŠcnico em PetrĂłleo e GĂĄs','M/T',3,30,359,30,104,0),
(2018,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M/T',2,30,62,28,111,18),
(2019,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',3,30,59,31,118,1),
(2019,'TĂŠcnico em PetrĂłleo e GĂĄs','M',2,30,412,28,105,19),
(2020,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',3,30,220,29,129,13),
(2020,'TĂŠcnico em PetrĂłleo e GĂĄs','M',2,30,311,30,122,18),
(2021,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',3,30,55,19,134,2),
(2021,'TĂŠcnico em PetrĂłleo e GĂĄs','I',2,30,214,30,128,25),
(2022,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',3,30,0,0,131,11),
(2022,'TĂŠcnico em PetrĂłleo e GĂĄs','I',2,30,240,29,126,20),
(2023,'TĂŠcnico em Agente ComunitĂĄrio de SaĂşde','M',3,30,0,0,10,1),
(2023,'TĂŠcnico em PetrĂłleo e GĂĄs','I',2,30,282,35,113,16),
(2024,'TĂŠcnico em PetrĂłleo e GĂĄs','I',2,30,322,37,125,18)


SELECT * FROM cursos # mostra a tabela 

SELECT AVG(matriculados) FROM cursos WHERE ano BETWEEN 2017 and 2020

SELECT
AVG(matriculados) AS 'Média Mat',
AVG(inscritos) AS 'Média Insc'
FROM cursos WHERE ano IN (2017, 2019, 2021)
GROUP BY curso
```

## Python e MySQL

### SQL

Linguagem declarativa, padronizada e baseada em tabelas

Principais usos: - criar e modificar estruturas de tabelas - consultar dados - inserir dados - atualizar dados - excluir dados

Outras funçőes: - fazer junçőes de tabelas - fazer uniőes de tabelas - operaçőes de agrupamento - operaçőes de filtragem

Sugestăo de material complementar: `https://www.w3schools.com/sql/`

### Tabelas

O conceito central do modelo relacional é a tabela, que organiza os dados de forma lógica e intuitiva em colunas e linhas:

- Colunas (Campos ou atributos): Representam as características de um dado (ex: número do processo, vara). Cada coluna possui um tipo de dado específico, conhecido como "Domínio de Dado" (ex: TEXTM INTEGER, REAL), que define o conjunto de valores possíveis.
- Linhas (Tuplas ou Registro): Representam uma instância individual de um dado, contendo os valores para cada coluna. Por exemplo, uma linha na tabela *processos* conteria '001234' para o número de um processo e 'Vara Cível de Curitiba' para o campo *vara*.

Exemplo Prático

- **foi realizado e está em outro arquivo**.

## Python e MySQL em Aplicaçăo de BI

Contexto: Criaremos um código Python para realizar a operaçăo de ETL dentro de um problema de Business Inteligence (Inteligęncia de Negócio).

Conceito utilizados em Python:

- conexăo com banco através da biblioteca pymysql;
- criaçăo de queries e views;
- exercuçăo de queries no python;
- importaçăo de pacotes;
- criaçăo de funçőes;
- boas práticas na criaçăo de scripts.

## Business Intelligence

Conjunto de processor e tecnologias que permitem a transformaçăo de dados em informaçăo, com o intuito de apoiar a tomada de decisőes.
Em BI, os dados săo coletados das bases de dados transicionais (sistemas) e armazenados em um DataWarehouse(DW).

- Bases Transacionais
- Data Warehouse
- Processo de BI
- Pacote PyMySQL
- Comandos Principais
- Estrutura de um script Python/MySQL